### PR TITLE
Add second title 

### PR DESCRIPTION
**Pull request by miguelriverasarmiento**
today I added the second title for the release

### CODE REVIEW

**Review by jjmedinas — COMMENTED** [review]
Why did you add all those `.ttf` files?
where are you using them?

**Comment by miguelriverasarmiento** [comment]
I am not using them, for now. do I delete them?

**Comment by jjmedinas** [comment]
> I am not using them, for now. do I delete them?

I'm seeing you are using just two of them, you should delete the others.

**Comment by miguelriverasarmiento** [comment]
ok I'm going to delete them

**Comment by miguelriverasarmiento** [comment]
try to delete with all commands but they were not deleted

**Comment by miguelriverasarmiento** [comment]
I uploaded a new commit with no unused files

**Review by jjmedinas — APPROVED** [review]

**Pull request merged**
